### ISSUE TITLE
complete 1.0.0 release blockers

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/secrets-helper#12]
Get this project ready for 1.0.0 release. :D

- [ ] #5 Add Windows testing and validate command processing
- [ ] #6 Advanced variable injection
- [ ] #7 Sanitize environment variable names
- [ ] #8 Finish docs
- [ ] #9 Add integration tests
- [ ] #10 Fix issues with mypy types
- [ ] #11 Add tests for handling of invalid config files

**Comment by mattsb42-aws** [comment]
https://github.com/awslabs/secrets-helper/milestone/1
